### ISSUE TITLE
FIx and improve documentation for new adapters

### ISSUE THREAD

**Issue by teonivalois** [hubotio/hubot#1439] opened 2018-04-11 16:08 UTC
I've tried to create an adapter. for myself, but after following all steps from https://hubot.github.com/docs/adapters/development/ all I get is _ERROR Cannot load adapter sample - Error: Cannot find module 'hubot-sample'_

Please update the documentation.

**Comment by loveonelong** [comment] 2018-09-10 10:58
You can see this about your problem.
Duplicate of #804 
I think the document is really too old too.

**Comment by joeyguerra** [comment] 2023-04-23 02:37
[Development](https://github.com/hubotio/hubot/blob/master/docs/adapters/development.md) has been updated for Javascript.

**Closed** 2023-05-31 01:39 UTC
Labels: documentation
