### ISSUE TITLE
Convert documentation to JavaScript (decaffinate)

### ISSUE THREAD

**Issue by rektide** [hubotio/hubot#1436] opened 2018-03-08 16:24 UTC
The docs should stop being a special ❄️ and switch to the language everyone knows and uses these days, to increase accessibility.

That said, [coffeescript is still remarkably present](http://redmonk.com/sogrady/2018/03/07/language-rankings-1-18/), but I expect a lot of this is legacy.

**Comment by abowail501** [comment] 2020-05-27 21:30
https://strawpoll.com/pgy9k5xk

Number 4- علي

**Comment by technicalpickles** [comment] 2023-04-18 14:19
Duplicate of https://github.com/hubotio/hubot/issues/1087

**Closed by technicalpickles** 2023-04-18 14:19 UTC
Labels: documentation
